name: coffee
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-42.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^5.1.0
  readmore: ^2.1.0
  http: ^1.1.0
  intl: ^0.18.1
  cloud_firestore: ^4.9.1
  image_picker: ^1.0.4
  firebase_storage: ^11.2.6

  flutter_image_compress: ^2.0.4
  flutter_rating_bar: ^4.0.1
  path_provider: ^2.1.1
  uuid: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets: 
    - assets/images/
  uses-material-design: true
